name: Testes Automatizados

on: push

jobs:
  rodar-testes:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar as bibliotecas do projeto
        run: pip install -r requirements.txt

      - name: Rodar os testes
        run: pytest